//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/05/24 - 18:04:13
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="bandejaagendaResult"/> and <see cref="bandejaagendaResultDto"/>.
    /// </summary>
    public static partial class bandejaagendaResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="bandejaagendaResultDto"/> converted from <see cref="bandejaagendaResult"/>.</param>
        static partial void OnDTO(this bandejaagendaResult entity, bandejaagendaResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="bandejaagendaResult"/> converted from <see cref="bandejaagendaResultDto"/>.</param>
        static partial void OnEntity(this bandejaagendaResultDto dto, bandejaagendaResult entity);

        /// <summary>
        /// Converts this instance of <see cref="bandejaagendaResultDto"/> to an instance of <see cref="bandejaagendaResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="bandejaagendaResultDto"/> to convert.</param>
        public static bandejaagendaResult ToEntity(this bandejaagendaResultDto dto)
        {
            if (dto == null) return null;

            var entity = new bandejaagendaResult();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.d_DateTimeCalendar = dto.d_DateTimeCalendar;
            entity.v_Pacient = dto.v_Pacient;
            entity.v_NumberDocument = dto.v_NumberDocument;
            entity.v_LineStatusName = dto.v_LineStatusName;
            entity.v_ServiceName = dto.v_ServiceName;
            entity.v_CalendarStatusName = dto.v_CalendarStatusName;
            entity.v_EsoTypeName = dto.v_EsoTypeName;
            entity.v_ServiceStatusName = dto.v_ServiceStatusName;
            entity.v_AptitudeStatusName = dto.v_AptitudeStatusName;
            entity.d_SalidaCM = dto.d_SalidaCM;
            entity.v_ServiceTypeName = dto.v_ServiceTypeName;
            entity.v_NewContinuationName = dto.v_NewContinuationName;
            entity.v_IsVipName = dto.v_IsVipName;
            entity.GESO = dto.GESO;
            entity.i_ServiceTypeId = dto.i_ServiceTypeId;
            entity.v_ProtocolName = dto.v_ProtocolName;
            entity.v_OrganizationLocationProtocol = dto.v_OrganizationLocationProtocol;
            entity.v_WorkingOrganizationName = dto.v_WorkingOrganizationName;
            entity.v_OrganizationLocationService = dto.v_OrganizationLocationService;
            entity.d_EntryTimeCM = dto.d_EntryTimeCM;
            entity.Puesto = dto.Puesto;
            entity.Nombres = dto.Nombres;
            entity.ApePaterno = dto.ApePaterno;
            entity.ApeMaterno = dto.ApeMaterno;
            entity.v_ProtocolId = dto.v_ProtocolId;
            entity.v_CalendarId = dto.v_CalendarId;
            entity.d_Birthdate = dto.d_Birthdate;
            entity.v_PersonId = dto.v_PersonId;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.i_ServiceStatusId = dto.i_ServiceStatusId;
            entity.v_CreationUser = dto.v_CreationUser;
            entity.i_MasterServiceId = dto.i_MasterServiceId;
            entity.PrecioTotalProtocolo = dto.PrecioTotalProtocolo;
            entity.v_OrganizationId = dto.v_OrganizationId;
            entity.v_ServiceId1 = dto.v_ServiceId1;
            entity.v_EmployerOrganizationId = dto.v_EmployerOrganizationId;
            entity.i_NewContinuationId = dto.i_NewContinuationId;
            entity.v_ComprobantePago = dto.v_ComprobantePago;
            entity.v_NroLiquidacion = dto.v_NroLiquidacion;
            entity.d_CircuitStartDate = dto.d_CircuitStartDate;
            entity.d_EntryTimeCM1 = dto.d_EntryTimeCM1;
            entity.i_CalendarStatusId = dto.i_CalendarStatusId;
            entity.i_IsVipId = dto.i_IsVipId;
            entity.i_StatusLiquidation = dto.i_StatusLiquidation;
            entity.i_LineStatusId = dto.i_LineStatusId;
            entity.RucEmpFact = dto.RucEmpFact;
            entity.i_Edad = dto.i_Edad;
            entity.MEDICO = dto.MEDICO;
            entity.MEDICO_ID = dto.MEDICO_ID;
            entity.CONSULTORIO = dto.CONSULTORIO;
            entity.VENDEDOR = dto.VENDEDOR;
            entity.IMPORTE = dto.IMPORTE;
            entity.HISTORIA = dto.HISTORIA;
            entity.COMPROBANTE = dto.COMPROBANTE;
            entity.PROTOCOLO = dto.PROTOCOLO;
            entity.CONDICION = dto.CONDICION;
            entity.SERVICIO = dto.SERVICIO;
            entity.i_IsFac = dto.i_IsFac;
            entity.DETALLE = dto.DETALLE;
            entity.v_EmergencyPhone = dto.v_EmergencyPhone;
            entity.v_ContactName = dto.v_ContactName;
            entity.v_ObservacionesAdicionales = dto.v_ObservacionesAdicionales;
            entity.MedicoDerivado = dto.MedicoDerivado;
            entity.Zona = dto.Zona;
            entity.Establecimiento = dto.Establecimiento;
            entity.VendedorExterno = dto.VendedorExterno;
            entity.Sexo = dto.Sexo;
            entity.column68 = dto.column68;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="bandejaagendaResult"/> to an instance of <see cref="bandejaagendaResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="bandejaagendaResult"/> to convert.</param>
        public static bandejaagendaResultDto ToDTO(this bandejaagendaResult entity)
        {
            if (entity == null) return null;

            var dto = new bandejaagendaResultDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.d_DateTimeCalendar = entity.d_DateTimeCalendar;
            dto.v_Pacient = entity.v_Pacient;
            dto.v_NumberDocument = entity.v_NumberDocument;
            dto.v_LineStatusName = entity.v_LineStatusName;
            dto.v_ServiceName = entity.v_ServiceName;
            dto.v_CalendarStatusName = entity.v_CalendarStatusName;
            dto.v_EsoTypeName = entity.v_EsoTypeName;
            dto.v_ServiceStatusName = entity.v_ServiceStatusName;
            dto.v_AptitudeStatusName = entity.v_AptitudeStatusName;
            dto.d_SalidaCM = entity.d_SalidaCM;
            dto.v_ServiceTypeName = entity.v_ServiceTypeName;
            dto.v_NewContinuationName = entity.v_NewContinuationName;
            dto.v_IsVipName = entity.v_IsVipName;
            dto.GESO = entity.GESO;
            dto.i_ServiceTypeId = entity.i_ServiceTypeId;
            dto.v_ProtocolName = entity.v_ProtocolName;
            dto.v_OrganizationLocationProtocol = entity.v_OrganizationLocationProtocol;
            dto.v_WorkingOrganizationName = entity.v_WorkingOrganizationName;
            dto.v_OrganizationLocationService = entity.v_OrganizationLocationService;
            dto.d_EntryTimeCM = entity.d_EntryTimeCM;
            dto.Puesto = entity.Puesto;
            dto.Nombres = entity.Nombres;
            dto.ApePaterno = entity.ApePaterno;
            dto.ApeMaterno = entity.ApeMaterno;
            dto.v_ProtocolId = entity.v_ProtocolId;
            dto.v_CalendarId = entity.v_CalendarId;
            dto.d_Birthdate = entity.d_Birthdate;
            dto.v_PersonId = entity.v_PersonId;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.i_ServiceStatusId = entity.i_ServiceStatusId;
            dto.v_CreationUser = entity.v_CreationUser;
            dto.i_MasterServiceId = entity.i_MasterServiceId;
            dto.PrecioTotalProtocolo = entity.PrecioTotalProtocolo;
            dto.v_OrganizationId = entity.v_OrganizationId;
            dto.v_ServiceId1 = entity.v_ServiceId1;
            dto.v_EmployerOrganizationId = entity.v_EmployerOrganizationId;
            dto.i_NewContinuationId = entity.i_NewContinuationId;
            dto.v_ComprobantePago = entity.v_ComprobantePago;
            dto.v_NroLiquidacion = entity.v_NroLiquidacion;
            dto.d_CircuitStartDate = entity.d_CircuitStartDate;
            dto.d_EntryTimeCM1 = entity.d_EntryTimeCM1;
            dto.i_CalendarStatusId = entity.i_CalendarStatusId;
            dto.i_IsVipId = entity.i_IsVipId;
            dto.i_StatusLiquidation = entity.i_StatusLiquidation;
            dto.i_LineStatusId = entity.i_LineStatusId;
            dto.RucEmpFact = entity.RucEmpFact;
            dto.i_Edad = entity.i_Edad;
            dto.MEDICO = entity.MEDICO;
            dto.MEDICO_ID = entity.MEDICO_ID;
            dto.CONSULTORIO = entity.CONSULTORIO;
            dto.VENDEDOR = entity.VENDEDOR;
            dto.IMPORTE = entity.IMPORTE;
            dto.HISTORIA = entity.HISTORIA;
            dto.COMPROBANTE = entity.COMPROBANTE;
            dto.PROTOCOLO = entity.PROTOCOLO;
            dto.CONDICION = entity.CONDICION;
            dto.SERVICIO = entity.SERVICIO;
            dto.i_IsFac = entity.i_IsFac;
            dto.DETALLE = entity.DETALLE;
            dto.v_EmergencyPhone = entity.v_EmergencyPhone;
            dto.v_ContactName = entity.v_ContactName;
            dto.v_ObservacionesAdicionales = entity.v_ObservacionesAdicionales;
            dto.MedicoDerivado = entity.MedicoDerivado;
            dto.Zona = entity.Zona;
            dto.Establecimiento = entity.Establecimiento;
            dto.VendedorExterno = entity.VendedorExterno;
            dto.Sexo = entity.Sexo;
            dto.column68 = entity.column68;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="bandejaagendaResultDto"/> to an instance of <see cref="bandejaagendaResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<bandejaagendaResult> ToEntities(this IEnumerable<bandejaagendaResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="bandejaagendaResult"/> to an instance of <see cref="bandejaagendaResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<bandejaagendaResultDto> ToDTOs(this IEnumerable<bandejaagendaResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
