//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/09/08 - 20:52:52
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="configuracionexamenpago"/> and <see cref="configuracionexamenpagoDto"/>.
    /// </summary>
    public static partial class configuracionexamenpagoAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="configuracionexamenpagoDto"/> converted from <see cref="configuracionexamenpago"/>.</param>
        static partial void OnDTO(this configuracionexamenpago entity, configuracionexamenpagoDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="configuracionexamenpago"/> converted from <see cref="configuracionexamenpagoDto"/>.</param>
        static partial void OnEntity(this configuracionexamenpagoDto dto, configuracionexamenpago entity);

        /// <summary>
        /// Converts this instance of <see cref="configuracionexamenpagoDto"/> to an instance of <see cref="configuracionexamenpago"/>.
        /// </summary>
        /// <param name="dto"><see cref="configuracionexamenpagoDto"/> to convert.</param>
        public static configuracionexamenpago ToEntity(this configuracionexamenpagoDto dto)
        {
            if (dto == null) return null;

            var entity = new configuracionexamenpago();

            entity.v_idPagoExam = dto.v_idPagoExam;
            entity.v_IdConfPago = dto.v_IdConfPago;
            entity.v_ComponentId = dto.v_ComponentId;
            entity.v_Observaciones = dto.v_Observaciones;
            entity.v_ObservacionesCambios = dto.v_ObservacionesCambios;
            entity.i_IsDeleted = dto.i_IsDeleted;
            entity.i_InsertUserId = dto.i_InsertUserId;
            entity.d_InsertDate = dto.d_InsertDate;
            entity.i_UpdateUserId = dto.i_UpdateUserId;
            entity.d_UpdateDate = dto.d_UpdateDate;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="configuracionexamenpago"/> to an instance of <see cref="configuracionexamenpagoDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="configuracionexamenpago"/> to convert.</param>
        public static configuracionexamenpagoDto ToDTO(this configuracionexamenpago entity)
        {
            if (entity == null) return null;

            var dto = new configuracionexamenpagoDto();

            dto.v_idPagoExam = entity.v_idPagoExam;
            dto.v_IdConfPago = entity.v_IdConfPago;
            dto.v_ComponentId = entity.v_ComponentId;
            dto.v_Observaciones = entity.v_Observaciones;
            dto.v_ObservacionesCambios = entity.v_ObservacionesCambios;
            dto.i_IsDeleted = entity.i_IsDeleted;
            dto.i_InsertUserId = entity.i_InsertUserId;
            dto.d_InsertDate = entity.d_InsertDate;
            dto.i_UpdateUserId = entity.i_UpdateUserId;
            dto.d_UpdateDate = entity.d_UpdateDate;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="configuracionexamenpagoDto"/> to an instance of <see cref="configuracionexamenpago"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<configuracionexamenpago> ToEntities(this IEnumerable<configuracionexamenpagoDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="configuracionexamenpago"/> to an instance of <see cref="configuracionexamenpagoDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<configuracionexamenpagoDto> ToDTOs(this IEnumerable<configuracionexamenpago> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
