//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/06/05 - 09:07:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="gethospsoplist_spResult"/> and <see cref="gethospsoplist_spResultDto"/>.
    /// </summary>
    public static partial class gethospsoplist_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="gethospsoplist_spResultDto"/> converted from <see cref="gethospsoplist_spResult"/>.</param>
        static partial void OnDTO(this gethospsoplist_spResult entity, gethospsoplist_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="gethospsoplist_spResult"/> converted from <see cref="gethospsoplist_spResultDto"/>.</param>
        static partial void OnEntity(this gethospsoplist_spResultDto dto, gethospsoplist_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="gethospsoplist_spResultDto"/> to an instance of <see cref="gethospsoplist_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="gethospsoplist_spResultDto"/> to convert.</param>
        public static gethospsoplist_spResult ToEntity(this gethospsoplist_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new gethospsoplist_spResult();

            entity.TipoDeIngreso = dto.TipoDeIngreso;
            entity.TipoProcedimiento = dto.TipoProcedimiento;
            entity.d_FechaIngreso = dto.d_FechaIngreso;
            entity.d_FechaHoraCirugia = dto.d_FechaHoraCirugia;
            entity.d_FechaHoraHospPac = dto.d_FechaHoraHospPac;
            entity.d_FechaAlta = dto.d_FechaAlta;
            entity.v_Paciente = dto.v_Paciente;
            entity.TipoDocumento = dto.TipoDocumento;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.HistoriaClinica = dto.HistoriaClinica;
            entity.Edad = dto.Edad;
            entity.v_Cie10 = dto.v_Cie10;
            entity.v_Diagnostico = dto.v_Diagnostico;
            entity.v_MedicoTratante = dto.v_MedicoTratante;
            entity.Especialidad = dto.Especialidad;
            entity.Monto = dto.Monto;
            entity.d_PagoMedico = dto.d_PagoMedico;
            entity.MedicoPago = dto.MedicoPago;
            entity.d_PagoPaciente = dto.d_PagoPaciente;
            entity.PacientePago = dto.PacientePago;
            entity.v_CIE10IdSalida = dto.v_CIE10IdSalida;
            entity.v_DiseasesNameSalida = dto.v_DiseasesNameSalida;
            entity.i_ProcedimientoSOP = dto.i_ProcedimientoSOP;
            entity.v_ProcedimientoSOP = dto.v_ProcedimientoSOP;
            entity.v_Servicio = dto.v_Servicio;
            entity.v_NroLiquidacion = dto.v_NroLiquidacion;
            entity.VendedorExterno = dto.VendedorExterno;
            entity.v_Comentariox = dto.v_Comentariox;
            entity.v_HopitalizacionId = dto.v_HopitalizacionId;
            entity.v_PersonId = dto.v_PersonId;
            entity.i_IsDeleted = dto.i_IsDeleted;
            entity.Value1 = dto.Value1;
            entity.Value2 = dto.Value2;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="gethospsoplist_spResult"/> to an instance of <see cref="gethospsoplist_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="gethospsoplist_spResult"/> to convert.</param>
        public static gethospsoplist_spResultDto ToDTO(this gethospsoplist_spResult entity)
        {
            if (entity == null) return null;

            var dto = new gethospsoplist_spResultDto();

            dto.TipoDeIngreso = entity.TipoDeIngreso;
            dto.TipoProcedimiento = entity.TipoProcedimiento;
            dto.d_FechaIngreso = entity.d_FechaIngreso;
            dto.d_FechaHoraCirugia = entity.d_FechaHoraCirugia;
            dto.d_FechaHoraHospPac = entity.d_FechaHoraHospPac;
            dto.d_FechaAlta = entity.d_FechaAlta;
            dto.v_Paciente = entity.v_Paciente;
            dto.TipoDocumento = entity.TipoDocumento;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.HistoriaClinica = entity.HistoriaClinica;
            dto.Edad = entity.Edad;
            dto.v_Cie10 = entity.v_Cie10;
            dto.v_Diagnostico = entity.v_Diagnostico;
            dto.v_MedicoTratante = entity.v_MedicoTratante;
            dto.Especialidad = entity.Especialidad;
            dto.Monto = entity.Monto;
            dto.d_PagoMedico = entity.d_PagoMedico;
            dto.MedicoPago = entity.MedicoPago;
            dto.d_PagoPaciente = entity.d_PagoPaciente;
            dto.PacientePago = entity.PacientePago;
            dto.v_CIE10IdSalida = entity.v_CIE10IdSalida;
            dto.v_DiseasesNameSalida = entity.v_DiseasesNameSalida;
            dto.i_ProcedimientoSOP = entity.i_ProcedimientoSOP;
            dto.v_ProcedimientoSOP = entity.v_ProcedimientoSOP;
            dto.v_Servicio = entity.v_Servicio;
            dto.v_NroLiquidacion = entity.v_NroLiquidacion;
            dto.VendedorExterno = entity.VendedorExterno;
            dto.v_Comentariox = entity.v_Comentariox;
            dto.v_HopitalizacionId = entity.v_HopitalizacionId;
            dto.v_PersonId = entity.v_PersonId;
            dto.i_IsDeleted = entity.i_IsDeleted;
            dto.Value1 = entity.Value1;
            dto.Value2 = entity.Value2;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="gethospsoplist_spResultDto"/> to an instance of <see cref="gethospsoplist_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<gethospsoplist_spResult> ToEntities(this IEnumerable<gethospsoplist_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="gethospsoplist_spResult"/> to an instance of <see cref="gethospsoplist_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<gethospsoplist_spResultDto> ToDTOs(this IEnumerable<gethospsoplist_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
