//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/09/08 - 20:52:31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getlistservicespay_spResult"/> and <see cref="getlistservicespay_spResultDto"/>.
    /// </summary>
    public static partial class getlistservicespay_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getlistservicespay_spResultDto"/> converted from <see cref="getlistservicespay_spResult"/>.</param>
        static partial void OnDTO(this getlistservicespay_spResult entity, getlistservicespay_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getlistservicespay_spResult"/> converted from <see cref="getlistservicespay_spResultDto"/>.</param>
        static partial void OnEntity(this getlistservicespay_spResultDto dto, getlistservicespay_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getlistservicespay_spResultDto"/> to an instance of <see cref="getlistservicespay_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getlistservicespay_spResultDto"/> to convert.</param>
        public static getlistservicespay_spResult ToEntity(this getlistservicespay_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getlistservicespay_spResult();

            entity.i_MasterServiceId = dto.i_MasterServiceId;
            entity.i_MasterServiceTypeId = dto.i_MasterServiceTypeId;
            entity.MedicoTratanteId = dto.MedicoTratanteId;
            entity.MedicoTratante = dto.MedicoTratante;
            entity.Direccion = dto.Direccion;
            entity.Telefono = dto.Telefono;
            entity.CMP = dto.CMP;
            entity.Paciente = dto.Paciente;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.Tipo = dto.Tipo;
            entity.v_ServiceComponentId = dto.v_ServiceComponentId;
            entity.r_CostoComponente = dto.r_CostoComponente;
            entity.Componente = dto.Componente;
            entity.TipoProtocolo = dto.TipoProtocolo;
            entity.Comprobante = dto.Comprobante;
            entity.d_Total = dto.d_Total;
            entity.GrupoId = dto.GrupoId;
            entity.Turno = dto.Turno;
            entity.CodigoId = dto.CodigoId;
            entity.Grupo = dto.Grupo;
            entity.TipoComprobante = dto.TipoComprobante;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getlistservicespay_spResult"/> to an instance of <see cref="getlistservicespay_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getlistservicespay_spResult"/> to convert.</param>
        public static getlistservicespay_spResultDto ToDTO(this getlistservicespay_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getlistservicespay_spResultDto();

            dto.i_MasterServiceId = entity.i_MasterServiceId;
            dto.i_MasterServiceTypeId = entity.i_MasterServiceTypeId;
            dto.MedicoTratanteId = entity.MedicoTratanteId;
            dto.MedicoTratante = entity.MedicoTratante;
            dto.Direccion = entity.Direccion;
            dto.Telefono = entity.Telefono;
            dto.CMP = entity.CMP;
            dto.Paciente = entity.Paciente;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.Tipo = entity.Tipo;
            dto.v_ServiceComponentId = entity.v_ServiceComponentId;
            dto.r_CostoComponente = entity.r_CostoComponente;
            dto.Componente = entity.Componente;
            dto.TipoProtocolo = entity.TipoProtocolo;
            dto.Comprobante = entity.Comprobante;
            dto.d_Total = entity.d_Total;
            dto.GrupoId = entity.GrupoId;
            dto.Turno = entity.Turno;
            dto.CodigoId = entity.CodigoId;
            dto.Grupo = entity.Grupo;
            dto.TipoComprobante = entity.TipoComprobante;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getlistservicespay_spResultDto"/> to an instance of <see cref="getlistservicespay_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getlistservicespay_spResult> ToEntities(this IEnumerable<getlistservicespay_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getlistservicespay_spResult"/> to an instance of <see cref="getlistservicespay_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getlistservicespay_spResultDto> ToDTOs(this IEnumerable<getlistservicespay_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
