//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2022/12/23 - 00:58:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getpacientesResult"/> and <see cref="getpacientesResultDto"/>.
    /// </summary>
    public static partial class getpacientesResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getpacientesResultDto"/> converted from <see cref="getpacientesResult"/>.</param>
        static partial void OnDTO(this getpacientesResult entity, getpacientesResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getpacientesResult"/> converted from <see cref="getpacientesResultDto"/>.</param>
        static partial void OnEntity(this getpacientesResultDto dto, getpacientesResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getpacientesResultDto"/> to an instance of <see cref="getpacientesResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getpacientesResultDto"/> to convert.</param>
        public static getpacientesResult ToEntity(this getpacientesResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getpacientesResult();

            entity.Id = dto.Id;
            entity.Nombre = dto.Nombre;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getpacientesResult"/> to an instance of <see cref="getpacientesResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getpacientesResult"/> to convert.</param>
        public static getpacientesResultDto ToDTO(this getpacientesResult entity)
        {
            if (entity == null) return null;

            var dto = new getpacientesResultDto();

            dto.Id = entity.Id;
            dto.Nombre = entity.Nombre;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getpacientesResultDto"/> to an instance of <see cref="getpacientesResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getpacientesResult> ToEntities(this IEnumerable<getpacientesResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getpacientesResult"/> to an instance of <see cref="getpacientesResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getpacientesResultDto> ToDTOs(this IEnumerable<getpacientesResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
