//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/09/03 - 02:35:37
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getpersonpersonalinformationeso_sResult"/> and <see cref="getpersonpersonalinformationeso_sResultDto"/>.
    /// </summary>
    public static partial class getpersonpersonalinformationeso_sResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getpersonpersonalinformationeso_sResultDto"/> converted from <see cref="getpersonpersonalinformationeso_sResult"/>.</param>
        static partial void OnDTO(this getpersonpersonalinformationeso_sResult entity, getpersonpersonalinformationeso_sResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getpersonpersonalinformationeso_sResult"/> converted from <see cref="getpersonpersonalinformationeso_sResultDto"/>.</param>
        static partial void OnEntity(this getpersonpersonalinformationeso_sResultDto dto, getpersonpersonalinformationeso_sResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getpersonpersonalinformationeso_sResultDto"/> to an instance of <see cref="getpersonpersonalinformationeso_sResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getpersonpersonalinformationeso_sResultDto"/> to convert.</param>
        public static getpersonpersonalinformationeso_sResult ToEntity(this getpersonpersonalinformationeso_sResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getpersonpersonalinformationeso_sResult();

            entity.Historia = dto.Historia;
            entity.Paciente = dto.Paciente;
            entity.Dni = dto.Dni;
            entity.Genero = dto.Genero;
            entity.LugarNacimiento = dto.LugarNacimiento;
            entity.FNacimiento = dto.FNacimiento;
            entity.EstadoCivil = dto.EstadoCivil;
            entity.NivelEstudios = dto.NivelEstudios;
            entity.Email = dto.Email;
            entity.Telefono = dto.Telefono;
            entity.Foto = dto.Foto;
            entity.Direccion = dto.Direccion;
            entity.Distrito = dto.Distrito;
            entity.Provincia = dto.Provincia;
            entity.Departamento = dto.Departamento;
            entity.Religion = dto.Religion;
            entity.Hijos = dto.Hijos;
            entity.MKT = dto.MKT;
            entity.Ocupacion = dto.Ocupacion;
            entity.Nacionalidad = dto.Nacionalidad;
            entity.ContactoEm = dto.ContactoEm;
            entity.TelefonoEm = dto.TelefonoEm;
            entity.IdPersona = dto.IdPersona;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getpersonpersonalinformationeso_sResult"/> to an instance of <see cref="getpersonpersonalinformationeso_sResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getpersonpersonalinformationeso_sResult"/> to convert.</param>
        public static getpersonpersonalinformationeso_sResultDto ToDTO(this getpersonpersonalinformationeso_sResult entity)
        {
            if (entity == null) return null;

            var dto = new getpersonpersonalinformationeso_sResultDto();

            dto.Historia = entity.Historia;
            dto.Paciente = entity.Paciente;
            dto.Dni = entity.Dni;
            dto.Genero = entity.Genero;
            dto.LugarNacimiento = entity.LugarNacimiento;
            dto.FNacimiento = entity.FNacimiento;
            dto.EstadoCivil = entity.EstadoCivil;
            dto.NivelEstudios = entity.NivelEstudios;
            dto.Email = entity.Email;
            dto.Telefono = entity.Telefono;
            dto.Foto = entity.Foto;
            dto.Direccion = entity.Direccion;
            dto.Distrito = entity.Distrito;
            dto.Provincia = entity.Provincia;
            dto.Departamento = entity.Departamento;
            dto.Religion = entity.Religion;
            dto.Hijos = entity.Hijos;
            dto.MKT = entity.MKT;
            dto.Ocupacion = entity.Ocupacion;
            dto.Nacionalidad = entity.Nacionalidad;
            dto.ContactoEm = entity.ContactoEm;
            dto.TelefonoEm = entity.TelefonoEm;
            dto.IdPersona = entity.IdPersona;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getpersonpersonalinformationeso_sResultDto"/> to an instance of <see cref="getpersonpersonalinformationeso_sResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getpersonpersonalinformationeso_sResult> ToEntities(this IEnumerable<getpersonpersonalinformationeso_sResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getpersonpersonalinformationeso_sResult"/> to an instance of <see cref="getpersonpersonalinformationeso_sResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getpersonpersonalinformationeso_sResultDto> ToDTOs(this IEnumerable<getpersonpersonalinformationeso_sResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
