//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/09/08 - 20:52:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getventasandagenda_spResult"/> and <see cref="getventasandagenda_spResultDto"/>.
    /// </summary>
    public static partial class getventasandagenda_spResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getventasandagenda_spResultDto"/> converted from <see cref="getventasandagenda_spResult"/>.</param>
        static partial void OnDTO(this getventasandagenda_spResult entity, getventasandagenda_spResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getventasandagenda_spResult"/> converted from <see cref="getventasandagenda_spResultDto"/>.</param>
        static partial void OnEntity(this getventasandagenda_spResultDto dto, getventasandagenda_spResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getventasandagenda_spResultDto"/> to an instance of <see cref="getventasandagenda_spResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getventasandagenda_spResultDto"/> to convert.</param>
        public static getventasandagenda_spResult ToEntity(this getventasandagenda_spResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getventasandagenda_spResult();

            entity.v_IdVenta = dto.v_IdVenta;
            entity.v_Mes = dto.v_Mes;
            entity.v_Correlativo = dto.v_Correlativo;
            entity.v_SerieDocumento = dto.v_SerieDocumento;
            entity.v_CorrelativoDocumento = dto.v_CorrelativoDocumento;
            entity.NroRegistro = dto.NroRegistro;
            entity.Documento = dto.Documento;
            entity.i_IdTipoDocumento = dto.i_IdTipoDocumento;
            entity.TipoDocumento = dto.TipoDocumento;
            entity.t_FechaRegistro = dto.t_FechaRegistro;
            entity.v_IdCliente = dto.v_IdCliente;
            entity.CodigoCliente = dto.CodigoCliente;
            entity.NombreCliente = dto.NombreCliente;
            entity.d_Total = dto.d_Total;
            entity.i_IdEstado = dto.i_IdEstado;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;
            entity.v_UsuarioModificacion = dto.v_UsuarioModificacion;
            entity.v_UsuarioCreacion = dto.v_UsuarioCreacion;
            entity.Moneda = dto.Moneda;
            entity.Saldo = dto.Saldo;
            entity.TieneGRM = dto.TieneGRM;
            entity.Origen = dto.Origen;
            entity.NroDocCliente = dto.NroDocCliente;
            entity.d_TipoCambio = dto.d_TipoCambio;
            entity.i_EstadoSunat = dto.i_EstadoSunat;
            entity.i_IdTipoOperacion = dto.i_IdTipoOperacion;
            entity.v_Concepto = dto.v_Concepto;
            entity.v_IdVendedor = dto.v_IdVendedor;
            entity.i_ClienteEsAgente = dto.i_ClienteEsAgente;
            entity.v_PlacaVehiculo = dto.v_PlacaVehiculo;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.CONSULTORIO_id = dto.CONSULTORIO_id;
            entity.CONSULTORIO = dto.CONSULTORIO;
            entity.ServicioType = dto.ServicioType;
            entity.ServicioTypeId = dto.ServicioTypeId;
            entity.Comprobante = dto.Comprobante;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getventasandagenda_spResult"/> to an instance of <see cref="getventasandagenda_spResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getventasandagenda_spResult"/> to convert.</param>
        public static getventasandagenda_spResultDto ToDTO(this getventasandagenda_spResult entity)
        {
            if (entity == null) return null;

            var dto = new getventasandagenda_spResultDto();

            dto.v_IdVenta = entity.v_IdVenta;
            dto.v_Mes = entity.v_Mes;
            dto.v_Correlativo = entity.v_Correlativo;
            dto.v_SerieDocumento = entity.v_SerieDocumento;
            dto.v_CorrelativoDocumento = entity.v_CorrelativoDocumento;
            dto.NroRegistro = entity.NroRegistro;
            dto.Documento = entity.Documento;
            dto.i_IdTipoDocumento = entity.i_IdTipoDocumento;
            dto.TipoDocumento = entity.TipoDocumento;
            dto.t_FechaRegistro = entity.t_FechaRegistro;
            dto.v_IdCliente = entity.v_IdCliente;
            dto.CodigoCliente = entity.CodigoCliente;
            dto.NombreCliente = entity.NombreCliente;
            dto.d_Total = entity.d_Total;
            dto.i_IdEstado = entity.i_IdEstado;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;
            dto.v_UsuarioModificacion = entity.v_UsuarioModificacion;
            dto.v_UsuarioCreacion = entity.v_UsuarioCreacion;
            dto.Moneda = entity.Moneda;
            dto.Saldo = entity.Saldo;
            dto.TieneGRM = entity.TieneGRM;
            dto.Origen = entity.Origen;
            dto.NroDocCliente = entity.NroDocCliente;
            dto.d_TipoCambio = entity.d_TipoCambio;
            dto.i_EstadoSunat = entity.i_EstadoSunat;
            dto.i_IdTipoOperacion = entity.i_IdTipoOperacion;
            dto.v_Concepto = entity.v_Concepto;
            dto.v_IdVendedor = entity.v_IdVendedor;
            dto.i_ClienteEsAgente = entity.i_ClienteEsAgente;
            dto.v_PlacaVehiculo = entity.v_PlacaVehiculo;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.CONSULTORIO_id = entity.CONSULTORIO_id;
            dto.CONSULTORIO = entity.CONSULTORIO;
            dto.ServicioType = entity.ServicioType;
            dto.ServicioTypeId = entity.ServicioTypeId;
            dto.Comprobante = entity.Comprobante;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getventasandagenda_spResultDto"/> to an instance of <see cref="getventasandagenda_spResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getventasandagenda_spResult> ToEntities(this IEnumerable<getventasandagenda_spResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getventasandagenda_spResult"/> to an instance of <see cref="getventasandagenda_spResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getventasandagenda_spResultDto> ToDTOs(this IEnumerable<getventasandagenda_spResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
