//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/09/08 - 20:52:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="obtenercamashopsResult"/> and <see cref="obtenercamashopsResultDto"/>.
    /// </summary>
    public static partial class obtenercamashopsResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="obtenercamashopsResultDto"/> converted from <see cref="obtenercamashopsResult"/>.</param>
        static partial void OnDTO(this obtenercamashopsResult entity, obtenercamashopsResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="obtenercamashopsResult"/> converted from <see cref="obtenercamashopsResultDto"/>.</param>
        static partial void OnEntity(this obtenercamashopsResultDto dto, obtenercamashopsResult entity);

        /// <summary>
        /// Converts this instance of <see cref="obtenercamashopsResultDto"/> to an instance of <see cref="obtenercamashopsResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="obtenercamashopsResultDto"/> to convert.</param>
        public static obtenercamashopsResult ToEntity(this obtenercamashopsResultDto dto)
        {
            if (dto == null) return null;

            var entity = new obtenercamashopsResult();

            entity.Habitacion = dto.Habitacion;
            entity.i_HabitacionId = dto.i_HabitacionId;
            entity.Precio = dto.Precio;
            entity.Comentarios = dto.Comentarios;
            entity.ESTADO = dto.ESTADO;
            entity.PERSONA = dto.PERSONA;
            entity.Fecha = dto.Fecha;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="obtenercamashopsResult"/> to an instance of <see cref="obtenercamashopsResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="obtenercamashopsResult"/> to convert.</param>
        public static obtenercamashopsResultDto ToDTO(this obtenercamashopsResult entity)
        {
            if (entity == null) return null;

            var dto = new obtenercamashopsResultDto();

            dto.Habitacion = entity.Habitacion;
            dto.i_HabitacionId = entity.i_HabitacionId;
            dto.Precio = entity.Precio;
            dto.Comentarios = entity.Comentarios;
            dto.ESTADO = entity.ESTADO;
            dto.PERSONA = entity.PERSONA;
            dto.Fecha = entity.Fecha;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenercamashopsResultDto"/> to an instance of <see cref="obtenercamashopsResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<obtenercamashopsResult> ToEntities(this IEnumerable<obtenercamashopsResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenercamashopsResult"/> to an instance of <see cref="obtenercamashopsResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<obtenercamashopsResultDto> ToDTOs(this IEnumerable<obtenercamashopsResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
